apiVersion: v1
kind: Namespace
metadata:
  name: jakepwalker-io
  labels:
    name: jakepwalker-io
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
  labels:
    name: ingress
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
  namespace: jakepwalker-io
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 4000
  selector:
    name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: jakepwalker-io
spec:
  replicas: 3
  selector: 
    matchLabels: 
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      containers:
      - name: backend
        image: hisashii/jakepwalker-backend
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 4000