---

### Docker Installation
- name: Add Docker GPG key.
  rpm_key:
    key: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg
    state: present

- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Install Docker.
  package:
    name: docker-ce
    state: latest

- name: Install Docker SDK
  pip:
    name:
      - docker
    state: latest
    extra_args: --ignore-installed

- name: Start/Enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

### kubectl Installation
- name: Download kubectl archive
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubectl_version }}/kubernetes-client-{{ kubectl_os }}-{{ kubectl_arch }}.tar.gz"
    checksum: "{{ kubectl_checksum_archive }}"
    dest: "{{ kubectl_tmp_directory }}"
  tags:
    - kubectl

- name: Unarchive kubernetes-client
  unarchive:
    src: "{{ kubectl_tmp_directory }}/kubernetes-client-{{ kubectl_os }}-{{ kubectl_arch }}.tar.gz"
    dest: "{{ kubectl_tmp_directory }}"
    remote_src: yes
  tags:
    - kubectl

- name: Copy kubectl binary to destination directory
  copy:
    src: "{{ kubectl_tmp_directory }}/kubernetes/client/bin/{{ item }}"
    dest: "{{ kubectl_bin_directory }}/{{ item }}"
    mode: "{{ kubectl_binary_mode }}"
    owner: "{{ kubectl_owner }}"
    group: "{{ kubectl_group }}"
    remote_src: yes
  with_items:
    - kubectl

### minikube Installation





- import_tasks: "{{service_name}}-k8s.yaml"
  when: run_k8s_cluster

