---

- name: Gather facts and set host group
  hosts: localhost
  connection: local
  user: root
  gather_facts: false

  tags:
      - stage

  vars_files:
      - vars/global.yaml
      - vars/jake-web.yaml

  tasks:

    - name: Gather facts about webserver instance
      ec2_instance_info:
        filters:
          "tag:type": webserver
          "instance-state-name": ["running"]
      register: ec2

    - name: Wait for SSH connection
      wait_for:
        host: "{{ec2.instances[0].public_ip_address}}"
        port: 22
        timeout: 120
        state: started

    - name: Add webserver instance to host group
      add_host:
        name: "{{ec2.instances[0].public_ip_address}}"
        groups: "{{host_group}}"

- name: Configure Webservers
  hosts: "{{host_group}}"
  user: "{{distro_user}}"
  become: yes
  gather_facts: true

  tags:
    - config

  vars_files:
    - vars/global.yaml
    - vars/jake-web.yaml

  pre_tasks:

    - name: Gather facts
      action: ec2_metadata_facts

  roles:
    - epel
    - common
    - git
    - docker
    - letsencrypt
    - nginx
